name: Test workflow on 2015MiniAOD branch - plain docker
on:
  pull_request:
    branches:
      - 2015MiniAOD
    
jobs:
  test_workflow:
    runs-on: ubuntu-latest
    name: PhysObjectExtractor test - plain docker
    steps:
      # chmod of the script before getting to the container
      - uses: actions/checkout@v3
      - name: Prepare
        run: |
          mkdir outputs
      # run the container with the script in the repository
      - name: Going to a container
        id: container
        run: |
          docker run -v $(pwd):/mnt/vol -w /home/cmsusr cmsopendata/cmssw_7_5_8_patch3-slc6_amd64_gcc491 /bin/bash /mnt/vol/commands.sh github python/poet_cfg.py True
          echo ls -l  `ls -l `
          cp *.root outputs
      # upload output file
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: output
          path: outputs/
